services:
  db:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - subzero-network
    restart: unless-stopped
   
  liquibase:
    image: liquibase/liquibase:latest
    depends_on:
      - db
    volumes:
      - /apps/device/liquibase:/liquibase/changelog
    command: >
      --changeLogFile=/liquibase/changelog/db.changelog-master.xml
      --url=jdbc:postgresql://db:5432/mydb
      --username=user
      --password=user
      update
    networks:
      - subzero-network
      
volumes:
  postgres-data:
    driver: local
networks:
  subzero-network:
    driver: bridge