

services:
  db:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network
    restart: unless-stopped

  liquibase:
    image: liquibase/liquibase:latest
    container_name: liquibase_migrations
    depends_on:
      - db
    volumes:
      - ./liquibase:/liquibase
    command: ["liquibase", "--defaultsFile=/liquibase/liquibase.properties", "update"]
    environment:
      - LIQUIBASE_COMMAND_LOG_LEVEL=info
    networks:
      - postgres-network
    restart: unless-stopped

volumes:
  postgres-data:
    driver: local

networks:
  postgres-network:
    driver: bridge
